VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
VIALRGB_ENABLE = yes




MIDI_ENABLE = yes
NKRO_ENABLE = no

CONSOLE_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
SPACE_CADET_ENABLE = yes
MAGIC_ENABLE = yes
COMMAND_ENABLE = yes

ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes
# RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes

SRC += features/mouse_turbo_click.c

MOUSEKEY_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes